""" create metarUpdates table

Revision ID: 0e028eedc6f3
Revises: 1294ad2d843a
Create Date: 2022-09-16 06:36:54.533939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e028eedc6f3'
down_revision = '1294ad2d843a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metar_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metar_updates')
    # ### end Alembic commands ###
