"""added metars table

Revision ID: 1294ad2d843a
Revises: 84301147f173
Create Date: 2022-09-16 01:25:39.759521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1294ad2d843a'
down_revision = '84301147f173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('observation_time', sa.String(length=128), nullable=True),
    sa.Column('metar_raw_text', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metar')
    # ### end Alembic commands ###
