"""empty message

Revision ID: 39f1bdafac70
Revises: d1dcec056ef1
Create Date: 2021-02-28 09:15:52.097691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f1bdafac70'
down_revision = 'd1dcec056ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.create_table('routine_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('entry_reader', sa.Integer(), nullable=True),
    sa.Column('entry_editor', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_reader'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_form_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('routine_form_id', sa.Integer(), nullable=True),
    sa.Column('routine_form_verion', sa.Integer(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('field_values', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nila_form')
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('user_groups', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=True)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=15), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'user_groups')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.create_table('nila_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('label', sa.VARCHAR(length=30), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('read_access_user', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['read_access_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routine_form_entry')
    op.drop_table('routine_form')
    # ### end Alembic commands ###
