"""empty message

Revision ID: 667ab69f684b
Revises: 39f1bdafac70
Create Date: 2021-02-28 09:39:59.391957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667ab69f684b'
down_revision = '39f1bdafac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('entry_reader', sa.Integer(), nullable=True),
    sa.Column('entry_editor', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_reader'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_first_name', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('routine_form')
    # ### end Alembic commands ###
