"""empty message

Revision ID: 7d7486632beb
Revises: 667ab69f684b
Create Date: 2021-06-29 18:03:58.039439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7486632beb'
down_revision = '667ab69f684b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('routine_form_id', sa.Integer(), nullable=True),
    sa.Column('routine_form_verion', sa.Integer(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('field_values', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('editor', sa.Integer(), nullable=True),
    sa.Column('entry_reader', sa.Integer(), nullable=True),
    sa.Column('entry_editor', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_reader'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routine_form')
    op.drop_table('routine_form_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_form_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=True),
    sa.Column('routine_form_id', sa.INTEGER(), nullable=True),
    sa.Column('routine_form_verion', sa.INTEGER(), nullable=True),
    sa.Column('reader', sa.INTEGER(), nullable=True),
    sa.Column('editor', sa.INTEGER(), nullable=True),
    sa.Column('field_values', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('last_updated_by', sa.INTEGER(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('is_primary IN (0, 1)'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=True),
    sa.Column('reader', sa.INTEGER(), nullable=True),
    sa.Column('editor', sa.INTEGER(), nullable=True),
    sa.Column('entry_reader', sa.INTEGER(), nullable=True),
    sa.Column('entry_editor', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('label', sa.VARCHAR(length=30), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('fields', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('last_updated_by', sa.INTEGER(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('is_primary IN (0, 1)'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entry_reader'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routine_screen')
    op.drop_table('routine_entry')
    # ### end Alembic commands ###
