"""adding admin flag

Revision ID: 84301147f173
Revises: 9e1e93452cd9
Create Date: 2022-09-15 07:44:52.467049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84301147f173'
down_revision = '9e1e93452cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_screen')
    op.drop_table('routine_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    op.create_table('routine_entry',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('routine_form_id', sa.INTEGER(), nullable=True),
    sa.Column('field_values', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_screen',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('fields', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
